"""Source des règles codables (phase 5). Génère regles/regles.json et regles/regles.md.
Usage : python3 recherche/_outils/regles_source.py
Chaque règle : id, domaine, condition, action, parametres, preuve (A-D), sources (clés de sources.json), limite."""
import json, os, sys, collections
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def r(id, domaine, condition, action, parametres, preuve, sources, limite):
    return dict(id=id, domaine=domaine, condition=condition, action=action, parametres=parametres, preuve=preuve, sources=sources, limite=limite)
REGLES = [
# ---------- 1. autorégulation de la charge ----------
r('autoreg-cible-rir', 'autoregulation', "exercice de force (type reps) sans RPE cible précisé par le coach",
  "arrêter les séries avant l'échec ; repère proposé : 2 à 3 répétitions en réserve (RPE 7-8), 3 à 4 pour un exercice explosif ; ne jamais proposer l'échec",
  {"rir_force": [2, 3], "rir_explosif": [3, 4], "echec": False}, 'B', ['robinson2024', 'grgic2022', 'refalo2023'],
  "la source montre que l'échec n'est pas nécessaire pour la force ; la cible précise de 2-3 n'en vient pas (repère proposé) ; essais sur des pratiquants de musculation, pas sur des endurants fatigués"),
r('autoreg-pas-proportionnel', 'autoregulation', "série terminée avec un écart d'au moins 2 répétitions en réserve par rapport à la cible (aujourd'hui : pas fixe de 2,5 kg)",
  "ajuster la série suivante de 2,5 % de la charge par répétition d'écart (arrondi au pas disponible), au lieu d'un pas fixe ; garder la charge si l'écart est de 0 ou 1",
  {"pct_par_rep": 2.5, "ecart_min_reps": 2, "arrondi": "pas de l'exercice"}, 'C', ['helms2018', 'cowley2025', 'zourdos2016'],
  "le coefficient de 2,5 % par répétition vient de la relation charge-répétitions (Epley), pas d'un essai sur l'ajustement série par série"),
r('autoreg-plafond-seance', 'autoregulation', "hausses successives de charge dans une même séance",
  "plafonner la hausse totale à +10 % de la charge de départ sur la séance ; au-delà, noter pour le coach au lieu d'augmenter",
  {"hausse_max_pct_seance": 10}, 'D', [],
  "plafond de prudence sans étude ; il sert aussi de garde-fou contre un bug (responsabilité du fait du logiciel)"),
r('autoreg-premiere-serie', 'autoregulation', "première série d'un exercice",
  "ne pas augmenter la charge sur le seul ressenti de la première série (souvent sous-estimé) ; attendre la série 2, sauf si l'athlète annonce 5 répétitions en réserve ou plus",
  {"serie_min_pour_hausse": 2, "exception_rir": 5}, 'B', ['mansfield2020', 'halperin2022'],
  "ralentit la mise à la bonne charge quand le coach a prescrit beaucoup trop léger"),
r('autoreg-serie-incomplete', 'autoregulation', "série incomplète (répétitions prévues non atteintes) ou 0 répétition en réserve",
  "baisser la charge de 5 % (ou d'un pas) pour la série suivante et ajouter 30 s de récupération ; si deux séries de suite sont incomplètes, arrêter l'exercice et le signaler au coach",
  {"baisse_pct": 5, "recup_plus_s": 30, "arret_apres": 2}, 'D', ['grgic2022'],
  "seuils de prudence ; l'échec répété n'apporte rien à la force chez l'endurant"),
r('autoreg-report-seance-suivante', 'autoregulation', "fin d'un exercice : charge finale différente de la charge prescrite",
  "proposer au coach la charge finale comme charge de départ de la prochaine séance ; ne rien changer sans sa validation",
  {"validation_coach": True}, 'D', ['helms2018'],
  "aujourd'hui l'appli note seulement « Nathan montera la prochaine fois »"),
r('autoreg-rir-correction-debutant', 'autoregulation', "athlète avec moins de 4 semaines de pratique du ressenti (RIR), ou série de plus de 12 répétitions",
  "traiter le RIR annoncé comme incertain à ±1 répétition ; pour les séries de plus de 12 répétitions, demander un RPE global plutôt qu'un RIR",
  {"incertitude_reps": 1, "reps_max_rir": 12, "semaines_apprentissage": 4}, 'B', ['halperin2022', 'zourdos2021'],
  "l'erreur individuelle varie beaucoup (hétérogénéité I² de 98 %) ; l'expérience n'améliore pas la précision"),
r('autoreg-tenues', 'autoregulation', "tenue (type hold) jugée trop facile (20 s en réserve ou plus) ou impossible (0 s)",
  "allonger de 5 s, ou raccourcir de 5 s (plancher 10 s) ; au-delà de 60 s de tenue, proposer la variante plus dure plutôt que d'allonger",
  {"pas_s": 5, "plancher_s": 10, "plafond_s": 60}, 'D', ['lum2019'],
  "c'est le comportement actuel de l'appli, plus le plafond de 60 s ; pas d'étude sur ce pas de 5 s"),
r('autoreg-charge-lourde-cible', 'autoregulation', "exercice principal de force en phase de développement (PPG, PPO), chez un athlète qui maîtrise la technique",
  "prescrire 3 à 6 répétitions à 80 % du max estimé ou plus ; signaler au coach une séance faite uniquement de séries de 12 répétitions et plus",
  {"reps": [3, 6], "pct_1rm_min": 80, "alerte_reps_min": 12}, 'B', ['eihara2022', 'llanoslagos2024b', 'llanoslagos2026'],
  "certitude de preuve faible en vélo ; ne vaut pas pour un débutant en musculation (voir debutant-charges) : il faut d'abord une phase d'apprentissage technique et une montée progressive"),
r('debutant-charges', 'autoregulation', "athlète débutant en musculation (moins de 3 mois de pratique encadrée)",
  "commencer par 8 à 12 répétitions à charge modérée, technique d'abord ; hausses de charge de 2 à 10 % ; pas de test de vrai 1RM",
  {"reps": [8, 12], "hausse_pct": [2, 10], "vrai_1rm": False, "mois_min": 3}, 'A', ['acsm2009'],
  "position de consensus ancienne (2009) ; le passage au lourd se décide avec le coach"),
# ---------- 2. progression proprio / plio ----------
r('proprio-niveau', 'progression-proprio-plio', "exercice de proprio à niveaux : réponse « trop facile » ou « je perds l'équilibre »",
  "monter d'un niveau après « trop facile » ; descendre d'un niveau après « je perds l'équilibre » ; rester sinon (comportement actuel)",
  {"niveaux": 4}, 'D', ['schiftan2015'],
  "la progression par ressenti n'est pas testée ; la preuve porte sur l'entraînement de l'équilibre en général"),
r('proprio-validation-niveau', 'progression-proprio-plio', "passage au niveau supérieur demandé pour la première fois",
  "exiger « trop facile » sur 2 séries de suite, ou sur 2 séances, avant de fixer le nouveau niveau comme niveau de départ",
  {"confirmations": 2}, 'D', [],
  "règle de prudence pour éviter les montées sur un coup de chance"),
r('proprio-cheville-fragile', 'progression-proprio-plio', "athlète qui a déclaré une entorse de cheville passée",
  "démarrer un niveau plus bas et programmer la proprio de cheville 2 à 3 fois par semaine pendant le bloc",
  {"niveau_depart": -1, "frequence_semaine": [2, 3]}, 'A', ['schiftan2015', 'doherty2017'],
  "la preuve concerne la récidive d'entorse dans des sports collectifs surtout ; pas de diagnostic par l'appli"),
r('plio-contacts-seance', 'progression-proprio-plio', "séance contenant de la pliométrie",
  "compter les contacts au sol ; débutant : 30 à 60 contacts de faible intensité par séance ; monter sur 3 à 4 semaines ; progresser par la difficulté des sauts plutôt que par le nombre",
  {"contacts_debut": [30, 60], "semaines_montee": [3, 4]}, 'D', ['ramirezcampillo2018'],
  "repère prudent, non prouvé ; les études décrivent mal les contacts"),
r('plio-plafond-bloc', 'progression-proprio-plio', "bloc de pliométrie de 8 à 10 semaines",
  "alerter le coach quand le cumul dépasse environ 1 000 contacts sur le bloc : plus de sauts n'apporte plus de gain de réactivité",
  {"contacts_bloc": 1000, "semaines": [8, 10]}, 'B', ['ramirezcampillo2023'],
  "méta-analyse sur le RSI, toutes populations ; peu de cyclistes"),
r('plio-qualite', 'progression-proprio-plio', "réponse « ça a bien baissé » ou « plus du tout explosif » après une série de sauts",
  "ajouter 30 s de récupération ; si la série suivante est encore dégradée, arrêter la pliométrie de la séance",
  {"recup_plus_s": 30, "arret_apres": 2}, 'D', ['parejablanco2017'],
  "le +30 s est le comportement actuel ; l'arrêt après 2 séries dégradées est une règle de prudence"),
r('plio-ordre-seance', 'progression-proprio-plio', "séance qui contient pliométrie ou exercices explosifs et force lourde",
  "placer la pliométrie et l'explosif en début de séance, après l'échauffement ; alerter si la plio est placée après un bloc d'endurance",
  {"ordre": ["echauffement", "plio", "force", "gainage"]}, 'A', ['schumann2022'],
  "la méta-analyse montre que la force explosive est la qualité la plus freinée par l'endurance, pas un ordre d'exercices précis"),
r('plio-os-cyclistes', 'progression-proprio-plio', "athlète qui ne fait que du vélo, sans course à pied ni sauts dans la semaine",
  "proposer par défaut une micro-séance de sauts d'environ 5 min, 3 à 5 fois par semaine, en plus de la force lourde ; ne pas la proposer en cas de fracture de fatigue passée ou de réponse « oui » aux questions de veille : avis médical d'abord",
  {"duree_min": 5, "frequence_semaine": [3, 5]}, 'C', ['hilkens2024', 'olmedillas2012', 'zamboni2024'],
  "données surtout transversales ; un seul essai ouvert (surtout des femmes, élite, sauts + collagène) ; intérêt moins établi pour le vététiste ; l'appli ne mesure rien et ne parle pas de fragilité osseuse"),
# ---------- 3. décharge ----------
r('decharge-frequence', 'decharge', "4 à 6 semaines de musculation sans semaine allégée",
  "proposer au coach une semaine de décharge : même fréquence, charges maintenues, volume réduit (séries) de 40 à 50 %",
  {"semaines_max": [4, 6], "volume_pct": [-50, -40], "frequence": "inchangée"}, 'D', ['bell2023', 'rogerson2024'],
  "repose sur une enquête et un consensus d'entraîneurs, pas sur des essais"),
r('decharge-pas-arret', 'decharge', "décharge programmée",
  "garder une séance allégée plutôt que supprimer la musculation de la semaine",
  {"seances_min": 1}, 'C', ['coleman2024'],
  "un seul essai, sur des pratiquants de musculation"),
r('decharge-bloc-volume-endurance', 'decharge', "semaine où le volume d'endurance prévu dépasse de plus de 30 % la moyenne des 4 semaines précédentes (stage, bloc)",
  "passer la musculation en mode maintien (1 séance, volume réduit) pendant ce bloc",
  {"hausse_endurance_pct": 30, "seances": 1}, 'C', ['ronnestad2012', 'wilson2012'],
  "le seuil de 30 % est un choix ; la preuve dit seulement que le gros volume d'endurance freine les gains de force"),
r('arret-prolonge', 'decharge', "aucune séance de musculation faite depuis plus de 3 semaines en période de compétition",
  "alerter le coach et proposer une séance de maintien courte",
  {"semaines_alerte": 3, "perte_semaines": 8}, 'C', ['ronnestad2016', 'ronnestad2010b'],
  "le seuil de 3 semaines est proposé ; l'étude porte sur 8 semaines d'arrêt, avec 7 cyclistes par groupe"),
r('reprise-apres-coupure', 'decharge', "reprise après 2 semaines ou plus sans musculation",
  "reprendre à environ 80 % des dernières charges, RIR +1, et prévenir des courbatures ; revenir aux charges d'avant en 2 séances",
  {"pct_charge": 80, "rir_plus": 1, "seances_retour": 2}, 'D', ['chesterton2022'],
  "valeurs de terrain ; la preuve citée porte sur les courbatures comme frein à l'adhésion"),
# ---------- 4. garde-fou de compétition ----------
r('course-a-affutage', 'competition', "course A dans les 7 à 21 jours",
  "passer en affûtage : volume de musculation réduit de 40 à 60 %, charges lourdes et fréquence maintenues ; dernière séance lourde courte entre J-10 et J-5 (repère proposé)",
  {"jours": [7, 21], "volume_pct": [-60, -40], "derniere_seance_j": [-10, -5]}, 'C', ['bosquet2007', 'wang2023', 'spiering2021'],
  "preuve A pour l'affûtage de l'endurance (1 à 3 semaines) ; l'application à la musculation de l'endurant est une extrapolation, et la date de la dernière séance est de niveau D"),
r('course-veille', 'competition', "veille ou avant-veille d'une course A ou B",
  "interdire force lourde, excentrique et pliométrie intense ; autoriser seulement une activation courte (10 à 15 min) ; ne jamais placer de test",
  {"jours": 2, "activation_min": [10, 15]}, 'C', ['devantierthomas2024', 'giandolini2016b'],
  "délai de 48 h tiré d'études de fatigue après musculation et descente, pas d'un essai sur la veille de course"),
r('course-b-allegee', 'competition', "course B dans les 5 jours",
  "garder la séance, sans excentrique lent ni nouveauté ; volume réduit d'un tiers ; pas de séance jambes dans les 72 h avant la course",
  {"jours": 5, "volume_pct": -33, "delai_h": 72}, 'D', ['devantierthomas2024'],
  "choix de terrain"),
r('course-c-rien', 'competition', "course C",
  "ne rien changer au plan de musculation, sauf la règle des 48 h avant la course pour les jambes",
  {"delai_h": 48}, 'D', [], "choix de terrain"),
r('apres-course', 'competition', "lendemain et surlendemain d'une course A ou d'un trail avec 1 000 m de descente ou plus",
  "pas de musculation lourde des jambes pendant 48 à 72 h ; proposer récupération active et mobilité",
  {"delai_h": [48, 72], "descente_m": 1000}, 'C', ['giandolini2016b', 'lemire2021'],
  "études descriptives de la fatigue après des descentes de trail ; extrapolé aux courses de VTT et de route"),
r('saison-maintien', 'competition', "phase de compétition (PPC) du plan de saison",
  "basculer en mode maintien : 1 séance par semaine, 1 à 2 séries par exercice, charge lourde conservée ; vérifier par un test de force en cours de saison",
  {"seances_semaine": 1, "series": [1, 2]}, 'C', ['ronnestad2010b', 'spiering2021'],
  "un essai de 6 cyclistes non randomisé et une revue narrative en population générale ; non testé en trail"),
r('test-pas-avant-course', 'competition', "séance de tests placée à moins de 3 jours d'une course",
  "refuser et proposer une autre date",
  {"jours": 3}, 'D', [], "règle déjà dans le contexte de l'appli (« jamais la veille d'une course »), étendue à 3 jours"),
# ---------- 5. espacement muscu / endurance ----------
r('interference-delai', 'planification', "séance de musculation des jambes lourde et séance clé d'endurance dans la même demi-journée",
  "informer le coach (information, pas alerte) : séparer quand c'est possible, au moins 3 h, mieux 6 h ou plus ; la musculation en premier si l'objectif du bloc est la force ; en cas de conflit, la séance clé d'endurance garde la priorité et la musculation se déplace",
  {"delai_min_h": 3, "delai_defaut_h": 6, "reglable_par_coach": True}, 'C', ['robineau2016', 'schumann2022', 'petre2021', 'murlasits2018'],
  "le repère de 6 h vient d'un seul essai chez des rugbymen amateurs, qui mesure les gains de force et non la qualité de la séance d'endurance ; l'appli ne connaît l'heure réelle des séances que si intervals.icu la donne"),
r('interference-seuil-apres-muscu', 'planification', "séance au seuil ou fractionné de course prévue dans les 8 h après une musculation lourde des jambes",
  "c'est le seul des trois délais qui déclenche un signal par défaut : proposer de décaler la musculation ; si possible attendre le lendemain",
  {"delai_h": 8, "signal_par_defaut": True}, 'C', ['palmer2001'],
  "une étude de 9 coureurs"),
r('interference-48h-seance-cle', 'planification', "première ou deuxième séance d'un bloc, ou séance inhabituelle (nouvel exercice, excentrique), suivie d'une séance clé dans les 48 h",
  "prévenir le coach et prescrire une charge prudente ; ne pas appliquer ce délai de 48 h aux séances habituelles, sinon la semaine ne tient plus",
  {"delai_h": 48, "seances_prudentes": 2}, 'C', ['devantierthomas2024'],
  "une étude ; l'effet diminue avec l'habitude"),
r('interference-trail-plus-strict', 'planification', "athlète de trail",
  "par prudence, séparer un peu plus la musculation des jambes et la course (marge réglable) ; ne pas en faire une règle différente par sport sans l'avis du coach",
  {"marge_h": 12, "reglable_par_coach": True}, 'C', ['wilson2012', 'lundberg2022', 'schumann2022'],
  "résultats contradictoires : une méta-analyse de 2012 trouve que la course interfère plus que le vélo, celle de 2022 ne trouve aucun effet du type d'endurance"),
r('charge-tsb-bas', 'planification', "TSB d'intervals.icu très bas pour l'athlète (sous son 10e centile sur 90 jours) le jour d'une séance de musculation",
  "proposer la version allégée de la séance (une série de moins par exercice) ; ne jamais annuler d'office",
  {"centile": 10, "fenetre_j": 90, "series": -1}, 'D', ['marchal2025', 'vermeire2022'],
  "le modèle CTL/ATL/TSB prédit mal la forme individuelle ; la charge de musculation y est mal représentée"),
r('charge-srpe-intervals', 'planification', "fin d'une séance de musculation",
  "calculer une charge = RPE de séance (0-10) × durée en minutes, nommée « charge sRPE » et stockée à part dans l'appli ; son envoi dans intervals.icu est une option du coach ; ne pas l'appeler TSS",
  {"formule": "rpe_seance * duree_min", "envoi_intervals": "option du coach"}, 'C', ['foster2001', 'haddad2017'],
  "le sRPE est validé en endurance et en sports collectifs (A) ; pour la musculation, aucune étude de validité n'a été ouverte ici (les temps de repos gonflent les minutes) ; l'unité n'est pas celle du TSS"),
r('pas-d-acwr', 'planification', "calcul d'un ratio charge aiguë / charge chronique",
  "ne pas l'afficher et ne déclencher aucune alerte dessus ; signaler seulement les hausses brusques de volume",
  {}, 'A', ['impellizzeri2020', 'wang2020'],
  "consensus critique : le ratio n'a pas de base causale"),
r('ajout-muscu-retrait-endurance', 'planification', "premier bloc de musculation d'un athlète qui n'en faisait pas",
  "suggérer au coach de retirer un peu de volume d'endurance (environ 1 h par semaine) plutôt que d'empiler",
  {"heures_retirees": 1}, 'C', ['yamamoto2010'],
  "revue de 5 essais ; la valeur d'une heure est un repère"),
# ---------- 6. score de forme ----------
r('forme-score', 'score-de-forme', "matin d'une séance : 5 réponses (sommeil, fatigue, courbatures, stress, humeur) saisies",
  "calculer un score 0-100 contre la base de l'athlète (28 jours) : vert ≥ 70 = garder ; orange 50-69 = alléger (une série de moins, RIR +1, plio divisée par 2) ; rouge < 50 = remplacer par mobilité, respiration, proprio facile",
  {"poids": {"sommeilQualite": 12, "sommeilDuree": 13, "fatigue": 20, "courbatures": 13, "stress": 6, "humeur": 6, "rpeVeille": 10, "vfc": 15, "tsb": 5}, "vert": 70, "orange": 50},
  'D', ['saw2016', 'duignan2020', 'craven2022'],
  "score non validé : aucun essai ne montre qu'il améliore la performance ; l'athlète peut toujours garder sa séance"),
r('forme-priorites', 'score-de-forme', "case « malade » cochée, ou un item à 1 sur 5, ou nuit de moins de 6 h avant une séance de l'après-midi ou du soir",
  "malade : repos, message « si ça dure, vois un médecin » ; item à 1 ou nuit courte : au mieux orange, avec le libellé « nuit courte : séance à adapter si tu te sens moins bien »",
  {"sommeil_h": 6, "item_min": 1, "reglable_par_coach": True}, 'C', ['craven2022', 'walsh2021', 'meeusen2013'],
  "le −7,6 % de performance est une moyenne qui va de la nuit courte à la nuit blanche ; l'effet d'une seule nuit un peu courte est mal connu ; le plafond « orange » est un choix de conception"),
r('forme-rodage', 'score-de-forme', "moins de 14 jours de réponses",
  "afficher « score en rodage » et utiliser l'échelle absolue ; pas d'alerte au coach",
  {"jours_min": 14}, 'D', ['plews2014'], "choix de conception"),
r('forme-vfc', 'score-de-forme', "VFC disponible dans intervals.icu",
  "ne l'utiliser que s'il y a au moins 3 mesures sur 7 jours ; moyenne 7 jours sous la moyenne 28 jours moins 1 écart-type : au mieux orange",
  {"mesures_min_7j": 3, "ecart_type": 1, "poids_max_pct": 15}, 'B', ['plews2014', 'kiviniemi2007', 'duking2021'],
  "la VFC guidée n'améliore pas nettement la performance ; chez les très entraînés, elle peut baisser en bonne forme"),
r('forme-affutage', 'score-de-forme', "semaine d'affûtage ou veille de course",
  "le score ne peut qu'alléger la séance, jamais ajouter du volume",
  {}, 'D', ['bosquet2007'], "choix de conception"),
# ---------- 7. alertes surmenage / REDs ----------
r('alerte-tendance-basse', 'alerte', "3 jours rouges de suite, ou moyenne sur 7 jours du score BRUT (non recentré sur la base) sous 55, ou moyenne 28 jours en baisse de plus de 10 points",
  "notifier le coach : « tendance basse cette semaine, on en parle ? » ; côté athlète : « parles-en à ton coach » ; ne jamais écrire « surentraînement » ; figer la base tant que la moyenne 28 jours baisse",
  {"rouges_consecutifs": 3, "moyenne_7j_brute": 55, "baisse_28j_points": 10}, 'D', ['meeusen2013'],
  "aucun marqueur ne détecte le surentraînement ; l'alerte se calcule sur le score brut, sinon une fatigue qui dure fait baisser la base et masque le signal"),
r('alerte-veille-energie', 'alerte', "réponse « oui » à une des questions de veille (fatigue qui dure, perte de poids non voulue, règles irrégulières, fracture de fatigue passée)",
  "afficher « parles-en à un médecin » ; ne pas afficher de score ni l'étiquette REDs ; ne jamais proposer de poids cible",
  {"questions": 4, "poids_cible": False}, 'A', ['mountjoy2023', 'hilkens2023'],
  "consensus du CIO ; l'appli ne dépiste pas, elle oriente"),
r('alerte-sommeil-bas', 'alerte', "sommeil sous la moyenne de l'athlète 7 jours de suite",
  "proposer au coach d'en parler (examens, stress, écrans) avant de toucher au plan",
  {"jours": 7}, 'B', ['gao2019', 'walsh2021'],
  "association mesurée chez des moins de 19 ans ; pas une cause"),
r('alerte-adhesion', 'alerte', "moins de 75 % des séances de force prévues faites sur 4 semaines",
  "alerter le coach, proposer la version courte (20 min) et un message positif pré-rédigé ; jamais de reproche à l'athlète",
  {"seuil_pct": 75, "fenetre_semaines": 4, "version_courte_min": 20}, 'A', ['viiala2026', 'milkman2021'],
  "75 % est un repère, pas un seuil mesuré : c'est la borne entre groupes d'études (terciles) dans une méta-analyse de programmes de prévention en sports collectifs"),
# ---------- 8. nutrition de fin de séance ----------
r('nutrition-muscu', 'nutrition', "fin d'une séance de musculation lourde ou de pliométrie",
  "conseiller 0,3 à 0,4 g de protéines par kg au repas suivant (dans les 2 h) et de boire à la soif ; glucides 0,5 à 1 g par kg au repas",
  {"proteines_g_kg": [0.3, 0.4], "glucides_g_kg": [0.5, 1.0], "delai_h": 2}, 'A', ['jager2017', 'morton2018'],
  "preuve A pour les protéines, D pour les glucides après la musculation ; repères généraux, pas une prescription"),
r('nutrition-double-seance', 'nutrition', "deuxième séance (endurance ou musculation) prévue moins de 8 h après",
  "conseiller environ 1 g de glucides par kg et par heure jusqu'à la 2e séance (4 h au plus), 0,3 g de protéines par kg, et environ 1,5 L de boisson par kg perdu",
  {"glucides_g_kg_h": 1.0, "heures_max": 4, "proteines_g_kg": 0.3, "boisson_l_par_kg_perdu": 1.5}, 'A', ['burke2017', 'craven2021'],
  "exige le poids de l'athlète ; la pesée avant et après est facultative"),
r('nutrition-veille-course', 'nutrition', "veille d'une course A de plus de 90 min",
  "conseiller environ 10 g de glucides par kg sur la journée (8 à 12), des aliments connus, pas d'alcool",
  {"glucides_g_kg_jour": [8, 12], "duree_course_min": 90}, 'B', ['bussau2002', 'kerksick2017'],
  "à adapter à la tolérance digestive ; renvoyer vers un diététicien pour un plan personnel"),
r('nutrition-jamais-poids', 'nutrition', "tout conseil de nutrition affiché par l'appli",
  "ne jamais afficher de poids cible, de déficit calorique ni de conseil de perte de poids ; ne jamais afficher de dose de complément comme une prescription",
  {"poids_cible": False, "doses_complements": False}, 'A', ['mountjoy2023'],
  "choix de sécurité : risque de déficit énergétique chez les jeunes athlètes d'endurance"),
r('nutrition-pas-de-froid-apres-muscu', 'nutrition', "conseils de récupération un jour où il y a une séance de musculation en phase de développement",
  "ne pas proposer de bain froid ce jour-là, quelle que soit l'autre séance ; le proposer seulement après une course, une séance d'endurance dure un jour sans musculation, ou entre deux jours de compétition",
  {"phases_sans_froid": ["PPG", "PPO"]}, 'B', ['malta2021', 'grgic2023', 'pinero2024'],
  "montré chez des pratiquants de musculation (92 % d'hommes), non testé chez l'endurant ; effet probable sur l'hypertrophie, moins sûr que sur la force"),
# ---------- 9. choix de la routine de récup ----------
r('recup-routine-zones', 'recuperation', "génération d'une routine Récup & mobilité",
  "écarter tout exercice dont une zone est déclarée douloureuse ; insister sur les zones « focus » du coach ; privilégier les muscles sollicités par la séance du jour",
  {"exclusion": "zones douloureuses", "priorite": ["focus", "seance du jour"]}, 'D', [],
  "logique de bon sens déjà dans l'appli ; aucune étude sur la composition d'une routine"),
r('recup-etirements-duree', 'recuperation', "étirement statique placé avant une séance de force ou de puissance",
  "limiter à 30 s par muscle et le faire suivre d'un échauffement dynamique ; réserver les étirements longs (60 s et plus) à l'après-séance ou à une séance à part",
  {"avant_max_s": 30, "long_min_s": 60}, 'A', ['behm2016'],
  "l'effet négatif des étirements longs est petit et bref ; l'étirement ne remplace pas le renforcement, mais les auteurs le recommandent quand même dans l'échauffement des sports de sprint"),
r('recup-respiration-apres-dur', 'recuperation', "fin d'une séance très dure (RPE de séance de 8 ou plus)",
  "ne pas proposer la respiration carrée ; proposer la respiration libre ou 5 min à 6 cycles par minute (5 s d'inspiration, 5 s d'expiration) comme option de confort",
  {"inspire_s": 5, "expire_s": 5, "duree_min": 5, "rpe_min": 8}, 'C', ['kasap2025', 'laborde2022'],
  "un seul essai de 40 étudiants : la respiration carrée donne une FC et un effort perçu plus hauts ; le 6 par minute ne fait pas récupérer plus vite que la respiration libre"),
r('recup-rouleau', 'recuperation', "choix « auto-massage » dans la routine",
  "le proposer pour le confort et les courbatures (5 à 12 min), sans promesse de performance",
  {"duree_min": [5, 12]}, 'A', ['dupuy2018', 'poppendieck2016'],
  "effet surtout sur le ressenti"),
r('recup-sommeil-court', 'recuperation', "nuit de 6 h ou moins signalée, séance prévue le soir",
  "proposer de faire la séance le matin, ou la version allégée le soir, si l'athlète se sent moins bien",
  {"sommeil_h": 6}, 'B', ['craven2022', 'walsh2021'],
  "effet net pour la nuit blanche et le réveil avancé, mal connu pour une nuit simplement courte ; grande variabilité individuelle"),
# ---------- 10. tests et retests ----------
r('test-frequence', 'tests', "planification des tests",
  "tests de force toutes les 6 à 8 semaines (fin de bloc) ; tests de mobilité toutes les 8 à 12 semaines ; mêmes heure, échauffement, matériel et montage du téléphone",
  {"force_semaines": [6, 8], "mobilite_semaines": [8, 12]}, 'D', ['hopkins2000', 'weir2005'],
  "la fréquence est un choix de terrain ; la preuve porte sur la nécessité de conditions identiques"),
r('test-sous-erreur-stable', 'tests', "changement entre deux tests inférieur à l'erreur de mesure du test (mdc)",
  "afficher « stable », sans féliciter ni alerter",
  {"champ": "mdc de tests.json"}, 'B', ['weir2005', 'hopkins2000'],
  "plusieurs mdc de l'appli ne sont pas vérifiables dans la littérature (assis-debout, pont, équilibre) ; celui de la rotation interne de hanche est trop optimiste (10° au lieu de 6°)"),
r('test-familiarisation', 'tests', "première passation d'un test de saut ou d'un test nouveau",
  "la marquer « découverte » et prendre la deuxième passation comme référence",
  {"passation_reference": 2}, 'B', ['munro2011'],
  "étudié pour les tests de saut"),
r('test-rm-conditions', 'tests', "test de max estimé",
  "série test de 3 à 6 répétitions, arrêt à 1 ou 2 répétitions en réserve ; refuser le calcul au-delà de 10 répétitions ou de 4 répétitions en réserve ; marge affichée ±5 % (±8 à 10 % si plus de 8 répétitions ou 3 en réserve)",
  {"reps": [3, 6], "rir": [1, 2], "reps_max": 10, "rir_max": 4, "marge_pct": 5, "marge_large_pct": [8, 10]}, 'B', ['reynolds2006', 'zourdos2021', 'halperin2022'],
  "l'équation d'Epley n'a pas de méta-analyse dédiée ; un max par exercice"),
r('test-max-mise-a-jour', 'tests', "nouveau max estimé qui diffère de moins de 5 % du précédent",
  "garder l'ancien max pour le calcul des charges en % ; ne le changer qu'après deux tests concordants ou un écart de plus de 5 %",
  {"seuil_pct": 5, "tests_concordants": 2}, 'B', ['reynolds2006', 'nuzzo2024'],
  "ralentit la progression des charges en % ; l'ajustement au RPE pendant la séance compense"),
# ---------- 11. asymétries ----------
r('asymetrie-confirmee', 'asymetrie', "écart gauche-droite au-dessus du seuil du test",
  "n'afficher l'écart comme « à travailler » que s'il dépasse le seuil sur 2 passations de suite, toujours du même côté ; texte neutre",
  {"passations": 2, "meme_cote": True}, 'B', ['reid2007', 'howe2020', 'parkinson2021'],
  "les seuils de 10 à 15 % sont arbitraires ; un écart isolé n'a pas de sens"),
r('asymetrie-pas-de-prediction', 'asymetrie', "affichage d'un résultat de test ou d'un écart",
  "ne jamais écrire qu'un test prédit une blessure ; écrire « ça montre quoi travailler »",
  {}, 'A', ['moran2017b', 'opar2021', 'guan2022'],
  "les tests de terrain ne prédisent pas la blessure à l'échelle individuelle"),
r('asymetrie-action', 'asymetrie', "asymétrie confirmée",
  "proposer au coach d'ajouter une série pour le côté faible sur les exercices unilatéraux et de commencer par ce côté ; retester en fin de bloc",
  {"series_plus_cote_faible": 1}, 'D', ['bishop2023'],
  "pas de preuve que réduire une asymétrie améliore la performance"),
# ---------- 12. douleurs ----------
r('douleur-pendant-exercice', 'douleur', "bouton « gêne » pressé pendant un exercice",
  "arrêter l'exercice, proposer l'alternative qui ne sollicite pas la zone, noter la zone et prévenir le coach",
  {"alternative": "première alternative hors zone"}, 'D', ['besomi2025'],
  "l'appli ne distingue pas une gêne d'une blessure : elle ne pose aucun diagnostic"),
r('douleur-retrait', 'douleur', "même zone signalée sur 2 séances de suite, ou gêne signalée au repos",
  "retirer les exercices de cette zone des séances à venir jusqu'à la décision du coach ; afficher « parles-en à un kiné ou à un médecin »",
  {"seances": 2}, 'D', ['besomi2025'],
  "seuil de prudence ; les coureurs ont tendance à continuer malgré la gêne"),
r('douleur-pas-de-programme-soin', 'douleur', "gêne au tendon ou au genou signalée",
  "ne pas lancer de programme « tendon » ou « genou » : orienter vers un kiné ; si le kiné valide, le coach peut prescrire une charge lente et lourde",
  {}, 'B', ['beyer2015', 'vandervlist2021', 'neal2024'],
  "ligne à ne pas franchir : un programme personnalisé destiné à soulager une pathologie est un dispositif médical"),
r('douleur-chute', 'douleur', "case « chute ou choc récent » cochée (VTT)",
  "bloquer les exercices du haut du corps concerné et demander un feu vert médical avant de reprendre",
  {}, 'C', ['braybrook2023'],
  "données d'épidémiologie des chutes en VTT, pas d'essai sur la reprise"),
r('plafond-progression-code', 'douleur', "toute charge proposée par l'appli (ajustement, charge en %, test)",
  "refuser une charge supérieure à 110 % de la plus lourde déjà réussie sur cet exercice, et tout saut de plus de 10 % entre deux séances sans validation du coach",
  {"plafond_pct_record": 110, "saut_max_pct": 10}, 'D', [],
  "garde-fou de sécurité logicielle (responsabilité en cas de bug), sans base scientifique"),
]
src = {s['cle'] for s in json.load(open(os.path.join(R, 'sources.json')))}
ids = [x['id'] for x in REGLES]
pb = [i for i in ids if ids.count(i) > 1] + [f"{x['id']} : source inconnue {k}" for x in REGLES for k in x['sources'] if k not in src]
pb += [f"{x['id']} : preuve A/B/C sans source" for x in REGLES if x['preuve'] in 'ABC' and not x['sources']]
if pb: print('\n'.join(sorted(set(pb)))); sys.exit(1)
json.dump(REGLES, open(os.path.join(R, 'regles', 'regles.json'), 'w'), ensure_ascii=False, indent=1)
NOMS = {'autoregulation': "Autorégulation de la charge (RPE / RIR)", 'progression-proprio-plio': "Progression et régression : proprio et pliométrie",
        'decharge': "Décharge, arrêt et reprise", 'competition': "Garde-fou de compétition", 'planification': "Espacement musculation / endurance et charge",
        'score-de-forme': "Score de forme du jour", 'alerte': "Alertes (non médicales)", 'nutrition': "Nutrition et récupération de fin de séance",
        'recuperation': "Choix de la routine de récupération", 'tests': "Tests et retests", 'asymetrie': "Asymétries", 'douleur': "Gênes, douleurs et sécurité"}
c = collections.Counter(x['preuve'] for x in REGLES)
o = ["# Règles codables\n",
     f"*{len(REGLES)} règles, générées par `_outils/regles_source.py` (source unique ; `regles.json` est le même contenu pour un programme). Preuve : A {c['A']} · B {c['B']} · C {c['C']} · D {c['D']}.*\n",
     "## Comment lire\n",
     "- **Condition** : ce que le programme observe. **Action** : ce qu'il fait ou propose. **Paramètres** : les nombres, modifiables par le coach.",
     "- **Preuve** : A consensus ou méta-analyses · B plusieurs essais · C peu d'études ou population éloignée · **D avis d'expert ou choix de conception**.",
     f"- **{c['D']} règles sur {len(REGLES)} sont de niveau D** : ce sont des choix de prudence ou de conception. C'est normal, et il faut le dire : la science donne les principes (charges lourdes, pas d'échec, délais), rarement les seuils exacts.",
     "- **Limite** : ce que la règle ne sait pas. À lire avant de coder.",
     "- Aucune règle ne pose de diagnostic. Les alertes disent « parles-en à ton coach », « à un kiné », « à un médecin ».\n",
     "## Ce que l'appli fait déjà, et ce que ces règles changent\n",
     "| Aujourd'hui (`adjust()` dans `docs/js/app.js`) | Règle proposée |", "|---|---|",
     "| Écart d'au moins 2 répétitions en réserve par rapport à la cible : ± 1 pas fixe (2,5 kg par défaut) | `autoreg-pas-proportionnel` : 2,5 % par répétition d'écart, arrondi au pas |",
     "| Aucun plafond de hausse dans la séance | `autoreg-plafond-seance` (+10 %) et `plafond-progression-code` (110 % du record) |",
     "| Ajustement dès la première série | `autoreg-premiere-serie` : pas de hausse avant la série 2 |",
     "| Série incomplète : − 1 pas | `autoreg-serie-incomplete` : − 5 %, + 30 s, arrêt après 2 séries incomplètes |",
     "| Fin d'exercice : « Nathan montera la prochaine fois » | `autoreg-report-seance-suivante` : charge finale proposée au coach |",
     "| Tenues : ± 5 s | `autoreg-tenues` : idem, avec un plafond à 60 s |",
     "| Plio dégradée : + 30 s de récup | `plio-qualite` : idem, puis arrêt après 2 séries dégradées |",
     "| Proprio : niveau ± 1 selon le ressenti | `proprio-niveau` (inchangé) + `proprio-validation-niveau` |\n"]
for d, nom in NOMS.items():
    rs = [x for x in REGLES if x['domaine'] == d]
    o.append(f"## {nom} ({len(rs)})\n")
    o.append("| Règle | Condition | Action | Paramètres | Preuve | Sources | Limite |"); o.append("|---|---|---|---|---|---|---|")
    for x in rs:
        par = '; '.join(f"{k} = {json.dumps(v, ensure_ascii=False)}" for k, v in x['parametres'].items()) or '—'
        o.append(f"| `{x['id']}` | {x['condition']} | {x['action']} | {par} | {x['preuve']} | {' '.join('[@'+k+']' for k in x['sources']) or '—'} | {x['limite']} |")
    o.append('')
open(os.path.join(R, 'regles', 'regles.md'), 'w').write('\n'.join(o))
print(len(REGLES), 'règles', dict(c), {d: sum(1 for x in REGLES if x['domaine'] == d) for d in NOMS})
